### ISSUE TITLE
Retrieving Contact actions by date

### ISSUE THREAD

**Issue by moudarir** [ActiveCampaign/activecampaign-api-php#100]
Hi,
I can retrieve the contact details by using
```php
return $this->ac->api('contact/view?id='.$contactId);
```
or
```php
return $this->ac->api('contact/list?'.$filters.'&limit='.$limit);
```
In my case, i just want to get contact details with certain actions filtering by date.

So, is there a way to retrieve `Contact actions` filtering by `date` or `date range` ?

Thanks in advance.

**Comment by bartboy011** [comment]
Hi @moudarir - unfortunately, our API does not allow for filtering in that way.
