### ISSUE TITLE
Docs 

### ISSUE THREAD

**Issue by pruyas-simplex** [ActiveCampaign/activecampaign-api-php#111]
Im trying to figure out how to add a tag for a contact, or how to get the list of list. I cannot find docs that explains how can I do that. is that possible?

**Comment by bartboy011** [comment]
@pruyas-simplex please see our API documentation here: https://www.activecampaign.com/api/example.php?call=contact_tag_add and here: https://www.activecampaign.com/api/example.php?call=list_list

**Comment by pruyas-simplex** [comment]
Thanks, was not being able to find those docs easily
