### ISSUE TITLE
Can't update field using personalisation tag

### ISSUE THREAD

**Issue by jamesflight** [ActiveCampaign/activecampaign-api-php#14]
Trying to sync a field using a personalisation tag has no effect on the field (I think I am using the correct syntax as specified in [api docs](http://www.activecampaign.com/api/example.php?call=contact_sync):

    <?php
    $ac = new ActiveCampaign('xxx', 'xxx');
    $array =  [
        'email' => 'email@gmail.com',
        'field[%care_type%,0]' => 'Value'
    ];
    $ac->api("contact/sync", $array);

I can make it work correctly by specifying the id instead:

    <?php
    $ac = new ActiveCampaign('xxx', 'xxx');
    $array =  [
        'email' => 'email@gmail.com',
        'field[3,0]' => 'Value'
    ];
    $ac->api("contact/sync", $array);

I could just be missing something obvious, but as far as I can tell from the docs, the first example should work.

Thanks

**Comment by jamesflight** [comment]
Has this been fixed yet?

**Comment by mthommes** [comment]
Yes, it's actually just an encoding issue. So as long as you encode the `field[]` portion, it should work.

So this:

`field[%care_type%,0]=Value`

... should be URL-encoded to:

`field%5B%25care_type%25%2C0%5D=Value`

Let us know if that still doesn't work! :+1:
