### ISSUE TITLE
example.php Not working for me

### ISSUE THREAD

**Issue by Pooldipmuhammad** [ActiveCampaign/activecampaign-api-php#16]
Hi 

am using active campaign api 

$activeCampaign->version(2);
$contacts_view = $activeCampaign->api("contact/list"); its working but when am applying filer its not working 

example:

$contacts_view = $activeCampaign->api("contact/list?email=hasanmarjan@gmail.com"); 
$contacts_view = $activeCampaign->api("contact/list?datetime=2015-03-10");

also i want to know a way how i can get the today added contact list.
Please mention any api call or way so i can know how many new contact add today?

I have also used version one by get the error

Result: FAILED
Message: Failed: Nothing is returned
The entire result printed out:

Array
(
    [result_code] => 0
    [result_message] => Failed: Nothing is returned
    [result_output] => serialize
)

Raw response printed out:

a:3:{s:11:"result_code";i:0;s:14:"result_message";s:27:"Failed: Nothing is returned";s:13:"result_output";s:9:"serialize";}

Please inform me if you need my api key and url

**Comment by mthommes** [comment]
Hi - my suggestion is this (hopefully it will work fine for you):

1. Create an Advanced Search segment through the ActiveCampaign UI (on the Contacts page) using whatever conditions you need.
2. Use that segment ID in the API URL, IE: `&filters[segmentid]=2`

Let me know if that doesn't work.

**Comment by Pooldipmuhammad** [comment]
Hi,

1. Can You please guide me how i can create segment using UI because i have not find any way to create segment.

2. I have perform all the operations using API i have no access for all users accounts so how i can create segments using UI.

3. Please Just Guide me or send me function that will help me to find today add contact using api.

Hopefully you can help me with code example not refer to Ui.

**Comment by mthommes** [comment]
On the Contacts page click the "Search contacts" box in the upper-right section. Then click "Advanced Search." After adding conditions and clicking "Search" the URL should show `?segmentid=123`. Copy that unique ID and use that for the segment ID.

Let us know if that doesn't answer your question.

**Comment by srdjevic** [comment]
Unfortunately you can not use segments if you can not create them through the UI first. There are no API calls to manage segments due to their complexity -- they have to be built using our interface.

If you are a main admin user on your account (username "admin"), and have other users in the system, you can use "admin|otherusernamehere" as your username and your admin password to log into the system as that user to setup the segment.

**Comment by Pooldipmuhammad** [comment]
Hi,

I think you misunderstand my question.
My Question:

Please Just Guide me or send me function that will help me to find today add contact using api.
Hopefully you can help me with code example not refer to Ui.

So Please just tell api having any method that will return today added contact.

Thanks 

Hasan

**Comment by mthommes** [comment]
Hi, are you [looking for this](http://www.activecampaign.com/api/example.php?call=contact_add)?

**Comment by Pooldipmuhammad** [comment]
Hi,

am looking for this one :+1: 

http://www.activecampaign.com/api/example.php?call=contact_list

with these filters 

date/time string
    //'filters[datetime]' => '2009-10-22',

    // Contacts *since* a specified date in the past (set status param): exact match - provide MySQL-formatted date/time string
    //'filters[since_datetime]' => '2009-10-22 00:00:00',

These filters not working

**Comment by mthommes** [comment]
Hi - there are issues with using filters other than `segmentid` (mainly server-related to giant lookups in our system), so our recommended approach is to use a segment for now (as I mentioned in my initial reply). We will investigate and see if we can improve the other filter issues.

**Comment by joshua-chavanne** [comment]
It would be super helpful if these methods and the general usage of more advanced functionality of the API wrapper would be given in further examples.  The code examples without using the API wrapper are really great, but the usage of routing in the API wrapper commands could really use a nice article! 

Got my use case going and may report back when I am done with my work, but ultimately a few more examples of querying against the list functionality for different endpoints would have been useful.

Cheers.
