### ISSUE TITLE
You are not authorized to access this file

### ISSUE THREAD

**Issue by n1co-dev** [ActiveCampaign/activecampaign-api-php#17]
Hi there, 

I've got an issue - any help would be appreciate - thanx in advance if you can help me 

```php
        $ac = new ActiveCampaign(ACTIVECAMPAIGN_URL, ACTIVECAMPAIGN_API_KEY);
        var_dump($ac->api("account/view")); // works fine
        var_dump($ac->api("list/list",array( "ids"=>"all"))); // works fine

        // Failed: Nothing is returned but i do have campaigns returned by the API explorer
        var_dump($ac->api("campaign/list",array( "ids"=>"all"))); 
        // Failed: Nothing is returned but i do have campaigns returned by the API explorer
        var_dump($ac->api("user/list",array( "ids"=>2684)));  // also tried with array("2684") as ids
        // ERROR
        var_dump($ac->api("user/view",array( "id"=>2684))); 
        // ERROR (email exists in our base)
        var_dump($ac->api("user/view",array( "email"=>"zz@zz.com"))); 
```

The message returned by the user/view function is 
> An unexpected problem occurred with the API request. Some causes include: invalid JSON or XML returned. Here is the actual response from the server: ---- <?xml version='1.0' encoding='utf-8'?>
<root><reauth>1</reauth><error>You are not authorized to access this file</error></root>

**Comment by mthommes** [comment]
Hi - it looks like these are all `GET` methods, meaning you don't need the second parameter for the `api()` method (which is used for `POST` vars). Updated example:

`$ac->api("list/list?ids=all");`

You can include the `GET` params like normal URL parameters. Let us know if that still doesn't work, or any other questions!

**Comment by n1co-dev** [comment]
Hi there,  

thanx for the answer. 

This works fine now
```
$ac->api("list/list?ids=all");
```

but the *user view function doesn't*

```
// XML message - you are not authorized
var_dump($ac->api("user/view?ids=3462")); // though id exists
// json message : «Failed: Nothing is returned»
var_dump($ac->api("user/view?email=XXXX@free.fr")); 
```

if i change ids parameter by id it doesn't throw an exception but i have the failed nothing is returned message

```
// nothing is returned (the api doc says it should be ids parameter)
var_dump($ac->api("user/view?id=3462")); 
```


thanx in advance for your help…

**Comment by mthommes** [comment]
Hi - I have verified this method works using my own account:

`$ac->api("user/view?id=1");`

Can you let us know the account you are using? If you'd prefer, please email help@activecampaign.com to provide this information.

**Comment by srdjevic** [comment]
Are you trying to fetch contacts or admin users? /user/view?id=1 would fetch an admin user (who can log into the system), where /contact/view?id=1234 will fetch a contact. As you will only have a couple of admin users most likely, by the id you are trying to fetch (3462), I assume you are looking for the contacts API call, not admin users.

**Comment by n1co-dev** [comment]
My god… How stupid of me !! 

Thanx very much @srdjevic and @mthommes
