### ISSUE TITLE
Path contact/view/email not working

### ISSUE THREAD

**Issue by danielbitzer** [ActiveCampaign/activecampaign-api-php#27]
I've tried a few different paths and I'm fairly sure this is a bug. 

    $contact = $ac->api('contact/view/email', array(
         'email'=>'hello@example.com'
    ));

To fix I'm adding the following method to class AC_Contact

    function view_email($params, $post_data) {
        $request_url = "{$this->url}&api_action=contact_view_email&api_output={$this->output}&{$params}";
        $response = $this->curl($request_url, $post_data);
        return $response;
    }

**Comment by mthommes** [comment]
Since this is a `GET` method, it would just be:

`$contact = $ac->api("contact/view?email=hello@example.com");`

We have a task open to improve this, as it would make sense to be able to pass `GET` parameters as the second parameter of `$ac->api()`, but for now that's limited to `POST` data.

**Comment by danielbitzer** [comment]
Fair enough. I did try that too, but for some reason $params was coming through as an empty string in the view() method.

**Comment by mthommes** [comment]
Hi, I tested this on one of my own accounts, and it seemed to work fine, so to continue troubleshooting, please [submit a support ticket](http://www.activecampaign.com/contact/) and mention this thread so it gets directed to me. I will need to see your full API request. Thanks! :+1:
