### ISSUE TITLE
New release needed

### ISSUE THREAD

**Issue by jamesflight** [ActiveCampaign/activecampaign-api-php#29]
A lot has changed since the 1.0.0 release over a year ago, could you create another?

This is important for those of us using composer as part of deployment, as it means we can be sure our dependencies are the same in all instances of our codebase.

**Comment by mthommes** [comment]
Hi, sorry for the delay here. We are trying to do this more consistently going forward. We have another version out now (`v1.1.0`) [here](https://packagist.org/packages/activecampaign/api-php).

Let us know of any questions!
