### ISSUE TITLE
How to load all tags

### ISSUE THREAD

**Issue by verygoodplugins** [ActiveCampaign/activecampaign-api-php#34]
Is there a way to query for all tags that have been set up in ActiveCampaign?

**Comment by mthommes** [comment]
Unfortunately, no. We don't have methods for retrieving only the tags themselves, however our `contact_view` and `contact_list` methods should return tags related to each individual contact.

**Comment by molinto** [comment]
https://SUBDOMAIN.api-us1.com/api/3/tags&api_key=API_KEY
