### ISSUE TITLE
contact/automation/list not included in this SDK

### ISSUE THREAD

**Issue by apeiniger** [ActiveCampaign/activecampaign-api-php#36]
I tried to access the contact_automation_list endpoint from the AC API (http://www.activecampaign.com/api/example.php?call=contact_automation_list) but couldn't find the corresponding function here, so it throws an error. Could this be added?

**Comment by apeiniger** [comment]
Any news on this?

**Comment by femiagbabiaka** [comment]
Hello! Sorry about the delay on this, I'll be pushing the changes shortly.

**Comment by apeiniger** [comment]
Awesome, thanks :)
