### ISSUE TITLE
When will the v2 be released for?

### ISSUE THREAD

**Issue by lazharichir** [ActiveCampaign/activecampaign-api-php#41]
Hi there,

I am signing up to an upgrade in AC soon and I am starting to prepare my custom WordPress plugin to move from my old emailing system to AC.

I can see that the v2 is in the pipeline but could you let me know when is the v2 planned to be released for?

Thanks!

**Comment by ac-pevans** [comment]
We have a few things planned for the public API coming up, although we don't have a timeframe quite yet. Sorry! You'll hear from us when we do have something to announce.

**Comment by lazharichir** [comment]
No worries. I started working with the current version and works good
enough for me :)

On Tue, 29 Mar 2016, 00:19 Peter Evans, <notifications@github.com> wrote:

> We have a few things planned for the public API coming up, although we
> don't have a timeframe quite yet. Sorry! You'll hear from us when we do
> have something to announce.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ActiveCampaign/activecampaign-api-php/issues/41#issuecomment-202622526>
>
-- 

Lazhar
*Founder, Lazhar Limited*

*Let's Connect:* +44(0)7474333368 | Facebook
<https://www.facebook.com/lazhar> | Instagram <http://instagram.com/lazhar>
 | Twitter <https://twitter.com/lazharichir> | Linkedin
<https://www.linkedin.com/in/lazhar>
*Breeding Business:* breedingbusiness.com
*Creative & Inbound Marketing:* lazhar.co <http://lazhar.co>

*Lazhar Limited is a company registered in England & Wales (Company No.
09740325)*

**Comment by molinto** [comment]
Version 3 is out soon too I think, eg:
https://SUBDOMAIN.api-us1.com/api/3/tags&api_key=API_KEY
