### ISSUE TITLE
how can i get list of all the lists using API key only?

### ISSUE THREAD

**Issue by andyideologi** [ActiveCampaign/activecampaign-api-php#42]
i need to get all the lists using API key so that i can add leads to particular list.

**Comment by molinto** [comment]
https://SUBDOMAIN.api-us1.com/admin/api.php?api_key=API_KEY&api_action=list_list&api_output=json&ids=all&full=1

http://www.activecampaign.com/api/example.php?call=list_paginator

**Comment by mattpramschufer** [comment]
Just to follow up on molinto's comment  Using this class you would do something like

```
public function getAcLists() {
		$params = [
			'ids'  => 'all',
			'full' => '1'
		];
		$lists  = $this->ac()->api( "list/list_", $params );
		return $lists;
}
```

**Comment by andyideologi** [comment]
thanks molinto , i found list paginator link helpful for me. 
And thank you mattpramschufer for the code.

**Comment by cptiwari20** [comment]
Thanks @mattpramschufer for sharing the idea.
