### ISSUE TITLE
Unknown command: singlesignon

### ISSUE THREAD

**Issue by rayflores** [ActiveCampaign/activecampaign-api-php#45]
attempting to show autologin screen... i am consistently getting this error: Unknown command: singlesignon 

I know that by getting to this step, I have all folder and classes included correctly, but I am very unsure on why this would be calling this error. 

assuming this function is NOT being called correctly:  https://github.com/ActiveCampaign/activecampaign-api-php/blob/master/includes/Auth.class.php#L17

from this step:  https://github.com/ActiveCampaign/example-reseller_account_manage/blob/master/index.php#L204

any guidance would be appreciated...

**Comment by rayflores** [comment]
i figured it out... i was 'still' using the reseller creds, when I needed to be using the account creds...

**Comment by molinto** [comment]
I do that all the time, use activecampaign.com instead of account.api-us1.com
