### ISSUE TITLE
How to display all the deals without page limit.

### ISSUE THREAD

**Issue by ampf21** [ActiveCampaign/activecampaign-api-php#48]
I want to get all the deals so i can count the total number of them from the API.
There is a limit of 20 records per page. I want to bypass it and get all the deals so i can count it.

I'm using this: https://appterra.api-us1.com/admin/api.php?api_action=deal_list&api_key={this is a secret}&full=1

Please help me. I've been browsing these for 2 days...

**Comment by ac-pevans** [comment]
In this version of the API, there is no call to select the number of deals. What I'd do in your shoes is I would actually keep a cache variable of the count; you would page through the list to build the count, but it could then persist for whatever period of time makes sense to you.

We're working on a new version of our public API which should offer a much more elegant solution to this problem (which I agree is a problem), so stay tuned.

**Comment by ampf21** [comment]
thanks. for now i create a custom php action in symfony. I loop the total number of pages then at the same time store the deals in an array variable.

**Comment by acollins1991** [comment]
Sorry to reopen this thread, but would you mind posting your solution to this problem @ampf21 ? It would be helpful for people having this problem, including myself.

I also need an easy way to access the pipeline and pipeline stage IDs for each listed deal, instead of having to get each deal individually.. Has there been an update on the new friendlier API you've mentioned @ac-pevans ?

Thanks

**Comment by ac-pevans** [comment]
There has been, @acollins1991! Just today, incidentally. I confess to waiting a bit to respond to your posting until the blog post was out, but here it is: http://www.activecampaign.com/blog/introducing-the-activecampaign-api-v3-deep-data/. You can dive into the docs here: https://developers.activecampaign.com/reference. 

A fair warning: this is not the entirety of our v1 API convert to v3, but it does show you what that structure will look like. I'm pretty excited for it to be fully rolled out, which should be completed soon!

**Comment by acollins1991** [comment]
@ac-pevans Amazing timing! 

Thanks for responding. I look forward to tinkering with the new API and the full release!
