### ISSUE TITLE
Update contact view

### ISSUE THREAD

**Issue by JuliusKoronci** [ActiveCampaign/activecampaign-api-php#49]
Hi, contact view by id or email is not working at all..the API was updated but the code not..for instance if I use contact/view and provide a param email ..it should resolve to contact_view_email but it resolves to contact_view and does not return any results if I want to view a contact by it's id I must use a trick to do it like contact/view?id= because if I use id in params it does not return anything

**Comment by ac-pevans** [comment]
Hey Julius,

This is working for me when I test it. Could you submit a ticket through your account? Please also submit the code you're using to issue the API request so we can check that out.

Thanks!
