### ISSUE TITLE
Unclear of how to use parameters

### ISSUE THREAD

**Issue by jonathan-s** [ActiveCampaign/activecampaign-api-php#51]
I was trying this `$fields = $ac->api("list/field/view", array("ids" => "all");` and it gave me no result at all. Then 40 minutes later in a moment of inspiration I tried this `$fields = $ac->api("list/field/view?ids=all");` which worked. Please document the behaviour! 

And I would much prefer the first way of doing things because it feels a lot more natural. 

(ping @ac-pevans)

**Comment by femiagbabiaka** [comment]
Thanks @jonathan-s! I've added some documentation here: (https://github.com/ActiveCampaign/activecampaign-api-php/pull/60). Could you let me know what you think?

**Comment by jonathan-s** [comment]
👍

**Comment by chrisbell08** [comment]
For anyone else who stumbles on this when trying to get a list of all lists this works for that too, 
ex. $this->ac->api('list/list?ids=all');

**Comment by cristiangrama** [comment]
Addressed in #60
