### ISSUE TITLE
Getting rid of CURLOPT_FOLLOWLOCATION in Connector class

### ISSUE THREAD

**Issue by micdobro** [ActiveCampaign/activecampaign-api-php#54]
This is more an issue with cURL, but use of this settings in the Connector class spits a warning and disables following of the ``Location`` header (and that I assume can have consequences). I do not care about possible compatibility with ``safe_mode``, as it is removed as of 5.4.0, but ``open_basedir`` is a good security add-on that I do not want to get rid of. 

Did you consider changing handling of ``Location`` - from the cURL ``CURLOPT_FOLLOWLOCATION`` to manual mode? (there are snippets available)

**Comment by ac-pevans** [comment]
I'm not sure that `CURLOPT_FOLLOWLOCATION` is strictly necessary here. You likely won't ever run into that when connecting to your own account.

**Comment by micdobro** [comment]
Thanks - that of course makes commenting out that line much easier (it's hard to know all your API responses ;).

**Comment by ac-pevans** [comment]
No problem! We have released version 1.3.1 of the API which removes FOLLOWLOCATION. Let us know if you run into any other issues.
