### ISSUE TITLE
segment/list throws error

### ISSUE THREAD

**Issue by haktansuren** [ActiveCampaign/activecampaign-api-php#56]
details can be found at https://github.com/ActiveCampaign/activecampaign-api-php/pull/55

**Comment by ac-pevans** [comment]
Hey Haktan,

I went over your pull request, and agree segment_list is not working the way it should be with the library. I have some thoughts about how to do this that goes in a different direction than your pull request; we have this logged in our internal issue tracker and we should have an update on this next week.

Thanks for reporting!

**Comment by ac-pevans** [comment]
This should be fixed in the latest version (1.3.2).
