### ISSUE TITLE
How to get tags through api

### ISSUE THREAD

**Issue by sumiitmalik** [ActiveCampaign/activecampaign-api-php#66]
This is request code:
$activecampaignObj->api('tags/list');

Response i got is :
An unexpected problem occurred with the API request. Some causes include: invalid JSON or XML returned. Here is the actual response from the server: ---- [{"id":1,"name":"Tag 1","count":0},{"id":2,"name":"Tag 2","count":0}]

**Comment by jaschaio** [comment]
Getting the same error, how did you resolve it?
