### ISSUE TITLE
Getting error "We are currently having some issues.  Please check back soon."

### ISSUE THREAD

**Issue by shamimhasan** [ActiveCampaign/activecampaign-api-php#68]
An unexpected problem occurred with the API request. Some causes include: invalid JSON or XML returned. Here is the actual response from the server: ---- <div align="center" style="font-size:12px; font-family:Arial;">We are currently having some issues.  Please check back soon.</div>

**Comment by ac-pevans** [comment]
@shamimhasan The best way to handle this would be to submit a support ticket with your account information mentioned there, as this is likely an issue affecting only your account. You can do that here: http://www.activecampaign.com/contact/?support
