### ISSUE TITLE
Uncaught RequestException, invalid JSON or XML returned.

### ISSUE THREAD

**Issue by danielrahman** [ActiveCampaign/activecampaign-api-php#71]
Hi, after launching my script to add contacts to Active Campaign through contact_sync this error occurres.

`Fatal error: Uncaught RequestException: An unexpected problem occurred with the API request. Some causes include: invalid JSON or XML returned. Here is the actual response from the server: ---- in C:\Users\uzivatel\Desktop\folder\name\includes\Connector.class.php:209 Stack trace: #0 C:\Users\uzivatel\Desktop\folder\name\includes\Contact.class.php(87): AC_Connector->curl('https://directa...', Array) #1 C:\Users\uzivatel\Desktop\folder\name\includes\ActiveCampaign.class.php(109): AC_Contact->sync('', Array) #2 C:\Users\uzivatel\Desktop\folder\name\functions.php(82): ActiveCampaign->api('contact/sync', Array) #3 C:\Users\uzivatel\Desktop\folder\name\AC-DB-NEW.php(10): contacts(Object(mysqli_result), Object(ActiveCampaign)) #4 {main} thrown in C:\Users\uzivatel\Desktop\folder\name\includes\Connector.class.php on line 209`

Any idea on how to fix that?

**Comment by cyblancevipul** [comment]
Hi, danielrahman 
what code is you did?

**Comment by ac-pevans** [comment]
@danielrahman sorry for the delay in responding to this! You should submit a support ticket for any further help, as we would need details about what the message was that you got back.
