### ISSUE TITLE
Send email to particular subscriber(contact)

### ISSUE THREAD

**Issue by ekhlascyblance** [ActiveCampaign/activecampaign-api-php#72]
I want to Send email to particular subscriber(contact).
not the Lists (not selecting Lists ) only selected subscriber(contact) of a Lists.
How to send Campaign email using API.

Is there any API for Send Campaign email to particular contact only.

**Comment by ac-pevans** [comment]
@ekhlascyblance it's possible to send to just a single contact! Check out our documentation for the API call `campaign_send` here: http://www.activecampaign.com/api/example.php?call=campaign_send

**Comment by cyblancevipul** [comment]
Hi Peter Evans
I know about campaign_send you mentioned API.
But for that i need campaign id first. And when i create campaign it need list ld so i want to send campaign without list id only contact.
Hope you understand.

**Comment by ekhlascyblance** [comment]
#72
Hi All
I know about campaign_send you mentioned API.
But for that i need campaign id first. And when i create campaign it need list ld so i want to send campaign without list id only contact.

In Issue #1 mthommes commented on Dec 21, 2012
Just an update for anyone else following this thread - campaign_send will only work if the campaign has sent already (completely finished and sent). If you are trying to use campaign_send prior to sending the actual campaign, it will return "Message not sent."

So my need is to create campaign and send or schedule email campaign at the same time when i select contact without lists.

Hope you understand all.

**Comment by ekhlascyblance** [comment]
#72 <https://github.com/ActiveCampaign/activecampaign-api-php/issues/72>
Hi All
I know about campaign_send you mentioned API.
But for that i need campaign id first. And when i create campaign it need
list ld so i want to send campaign without list id only contact.

*In Issue #1
<https://github.com/ActiveCampaign/activecampaign-api-php/issues/1>
mthommes commented on Dec 21, 2012*
Just an update for anyone else following this thread - *campaign_send will
only work if the campaign has sent already (completely finished and sent).*
If you are trying to use campaign_send prior to sending the actual
campaign, it will return "Message not sent."

*So my need is to create campaign and send or schedule email campaign at
the same time when i select contact without lists.*

Hope you understand all.

**Comment by ac-pevans** [comment]
@ekhlascyblance That's correct, you do need to create a list. That isn't something you can avoid.

**Comment by cyblancevipul** [comment]
ok
Thanks Peter.

**Comment by j05u3** [comment]
Hi @ekhlascyblance, sorry, just wanted to ask how you ended up solving this problem

**Comment by j05u3** [comment]
Btw, is there any way to send an email/campaign using the API v3? I couldn't find any, thanks in advance ✌️

**Comment by dharmishtha-chhatrodiya** [comment]
Send email to particular subscriber(contact) in node js?

**Comment by j05u3** [comment]
> Send email to particular subscriber(contact) in node js?

Yep

**Comment by dcalvom** [comment]
Hi there, you guys were able to send a message to a particular contact in node.js using v3 API?

**Comment by j05u3** [comment]
> Hi there, you guys were able to send a message to a particular contact in node.js using v3 API?

Hi, not from my part, I ended up switching to a different service

**Comment by luchomatic** [comment]
Shouldn't sending an email/campaign to a contact be a pretty common use case for a campaigns mailer service?
