### ISSUE TITLE
Reopen #72

### ISSUE THREAD

**Issue by cyblancevipul** [ActiveCampaign/activecampaign-api-php#73]
Send email to particular subscriber(contact).

Hi Peter Evans
I know about campaign_send you mentioned API.
But for that i need campaign id first. And when i create campaign it need list ld so i want to send campaign without list id only contact.

**In Issue #1 mthommes commented on Dec 21, 2012**
Just an update for anyone else following this thread - **campaign_send will only work if the campaign has sent already (completely finished and sent).** If you are trying to use campaign_send prior to sending the actual campaign, it will return "Message not sent."

**So my need is to create campaign and send or schedule email campaign at the same time when i select contact without lists.** 
 
Hope you understand Now.

**Comment by ac-pevans** [comment]
@cyblancevipul Closing this as we are not looking to change the current behavior of this API call.
