### ISSUE TITLE
CURL not timing out, wrapper stuck 'indefinitely'

### ISSUE THREAD

**Issue by Jkwakkel** [ActiveCampaign/activecampaign-api-php#76]
Currently having an issue where there is a connection made to the API, but the API is very slow (Been loading for a few minutes). This in turn block the whole website. 

I suggest adding the following to the curl function

`curl_setopt($ch, CURLOPT_CONNECTTIMEOUT ,0); `
`curl_setopt($ch, CURLOPT_TIMEOUT, 10);`

So that if after 10 second in total CURL will stop. 10 seconds should be long enough for this API.

**Comment by Jkwakkel** [comment]
Created a fork and made it 8 second. Will see how it goes once the API is fully operating again.

**Comment by mthommes** [comment]
Hello! We did have some minor API availability issues the last couple of days, but we believe that to be resolved now. Are you still experiencing this issue consistently?

**Comment by cristiangrama** [comment]
Addressed in #78
