### ISSUE TITLE
contact/sync responses with "You are not authorized to access this file"

### ISSUE THREAD

**Issue by ckidow** [ActiveCampaign/activecampaign-api-php#8]
It is possible to get (list) the lists and add a list but everything else ends up in a "You are not authorized to access this file" - Response.

I executed the examples.php and got following output:

"Credentials valid! Proceeding...

stdClass Object
(
    [result_code] => 0
    [result_message] => You are not authorized to access this file
    [result_output] => json
    [http_code] => 200
    [success] => 0
    [error] => You are not authorized to access this file
)
List added successfully (ID 7)!

Syncing contact failed. Error returned: You are not authorized to access this file"
# Important Notice:

I executed this script locally from my computer within a virtual host and the active campaign installation runs remotely accessible.

**Comment by nilneelam** [comment]
Hello, I am facing same issue, not authorize to access contact list /sync 
Response - a:3:{s:11:"result_code";i:0;s:14:"result_message";s:42:"You are not authorized to access this file";s:13:"result_output";s:9:"serialize";}

**Comment by bartboy011** [comment]
@nilneelam This looks to be an issue with the API key that you're using - can you confirm that they are accurate?
