### ISSUE TITLE
Customer Product Purchase Details

### ISSUE THREAD

**Issue by vinu-ganesan** [ActiveCampaign/activecampaign-api-php#98]
Hi,
How to send the product order details like product name, price, etc through the API when creating the contact. Kindly help.
Thanks!

**Comment by bartboy011** [comment]
Hi @vinu-ganesan, unfortunately the v1 API does not handle any ecommerce data. Please take a look at our v3 API which does.

https://developers.activecampaign.com/reference

**Comment by vinu-ganesan** [comment]
Thank you @bartboy011
