### ISSUE TITLE
Deal Asignment in Activecampaign is not working

### ISSUE THREAD

**Issue by EIU-usa** [ActiveCampaign/activecampaign-api-php#99]
Activecampaign is assignig the deals to a wrong user since 22 days ago. We have contacted support 3 times and they don't have any solution.

Also, service is really slow, and it is difficult to work with it.

Not recommended as CRM.

**Comment by irufus** [comment]
@EIU-usa they don't have a solution or did they say they'll get back to you?

**Comment by bartboy011** [comment]
@EIU-usa Hey all, I'm sorry to hear that you're having issues with the platform. Is this related in any way to this API wrapper? I'm happy to reach out to our support staff and let them know that you're needing a solution, but if this is not related to the wrapper I'll need to close this Issue.

**Comment by EIU-usa** [comment]
They said they will contact me, but as you can see it is an ensolved problem since more than a year ago:

https://community.activecampaign.com/t/round-robin-limitations-issues/2627
________________________________
De: Ishmael Rufus <notifications@github.com>
Enviado: jueves, 10 de mayo de 2018 10:50 a. m.
Para: ActiveCampaign/activecampaign-api-php
Cc: EIU-usa; Mention
Asunto: Re: [ActiveCampaign/activecampaign-api-php] Deal Asignment in Activecampaign is not working (#99)


@EIU-usa<https://github.com/EIU-usa> they don't have a solution or did they say they'll get back to you?

**Comment by bartboy011** [comment]
@EIU-usa Thanks for the update, I'll make sure that this is internally brought to their attention. In the meantime, I'll close this issue ticket. Thank you!
